blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://fumadocs.vercel.app/
    about: Check out the Fumadocs documentation for help with the framework
  - name: Discussions
    url: https://github.com/fuma-nama/fumadocs/discussions
    about: Ask questions and share ideas in the Fumadocs community
